## pipelines >> stages >> jobs >> tasks/steps
trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo first job
  - job: SecondJob
    steps:
    - bash: echo second job
- stage: DevDeploy
  dependsOn: build
  jobs:
  - job: DevJob
    steps:
    - bash: echo DevJob
- stage: QADeploy
  dependsOn: build
  jobs:
  - job:
    steps:
    - bash: echo QAJob
- stage: ProdDeploy
  dependsOn: 
  - DevDeploy
  - QADeploy
  jobs:
  - job: ProdJob
    steps:
    - bash: echo prodjob